version: '3'

services: 
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./src:/usr/share/nginx/html
    depends_on:
      - php-fpm

  php-fpm:
    build: ./php-fpm
    volumes:
      - ./src:/usr/share/nginx/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password    
    ports:
      - 3306:3306
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lamp_db
      - MYSQL_USER=lamp_user
      - MYSQL_PASSWORD=lamp_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    depends_on: 
      - mysql 

volumes:
  mysql_data:
